In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
data

[[1, 2], [3, 4]]

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [7]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.5292, 0.8574],
        [0.6801, 0.0910]])



With random or constant values --->

In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.2928, 0.3338, 0.3409],
        [0.1510, 0.2608, 0.7484]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



Attributes of a Tensor --->

In [11]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Operations on Tensors --->

In [12]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [14]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last comun: ', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last comun:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
